#see https://github.com/Digilent/Cmod-A7-35T-GPIO/blob/master/src/constraints/CmodA7_Master.xdc

set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[0]}]

set_property PULLUP true [get_ports {adc_data[13]}]
set_property PULLUP true [get_ports {adc_data[12]}]
set_property PULLUP true [get_ports {adc_data[11]}]
set_property PULLUP true [get_ports {adc_data[10]}]
set_property PULLUP true [get_ports {adc_data[9]}]
set_property PULLUP true [get_ports {adc_data[8]}]
set_property PULLUP true [get_ports {adc_data[7]}]
set_property PULLUP true [get_ports {adc_data[6]}]
set_property PULLUP true [get_ports {adc_data[5]}]
set_property PULLUP true [get_ports {adc_data[4]}]
set_property PULLUP true [get_ports {adc_data[3]}]
set_property PULLUP true [get_ports {adc_data[2]}]
set_property PULLUP true [get_ports {adc_data[1]}]
set_property PULLUP true [get_ports {adc_data[0]}]

set_property PACKAGE_PIN U8 [get_ports {adc_data[13]}]
set_property PACKAGE_PIN W7 [get_ports {adc_data[12]}]
set_property PACKAGE_PIN U7 [get_ports {adc_data[11]}]
set_property PACKAGE_PIN U3 [get_ports {adc_data[10]}]
set_property PACKAGE_PIN W6 [get_ports {adc_data[9]}]
set_property PACKAGE_PIN U2 [get_ports {adc_data[8]}]
set_property PACKAGE_PIN U5 [get_ports {adc_data[7]}]
set_property PACKAGE_PIN J3 [get_ports {adc_data[6]}]
set_property PACKAGE_PIN A14 [get_ports {adc_data[5]}]
set_property PACKAGE_PIN B15 [get_ports {adc_data[4]}]
set_property PACKAGE_PIN A15 [get_ports {adc_data[3]}]
set_property PACKAGE_PIN H1 [get_ports {adc_data[2]}]
set_property PACKAGE_PIN C15 [get_ports {adc_data[1]}]
set_property PACKAGE_PIN K3 [get_ports {adc_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {adc_of}]
set_property PULLUP true [get_ports {adc_of}]
set_property PACKAGE_PIN V8 [get_ports {adc_of}]


set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
#set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
#set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]

set_property PACKAGE_PIN A16 [get_ports adc_clk]
#set_property PACKAGE_PIN T18 [get_ports reset_rtl]
#set_property PACKAGE_PIN Y9 [get_ports sys_clock]

set_property DRIVE 12 [get_ports adc_clk]
set_property SLEW SLOW [get_ports adc_clk]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property PACKAGE_PIN M3 [get_ports i2c_scl_io]
set_property PACKAGE_PIN L3 [get_ports i2c_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sda_io]
set_property OFFCHIP_TERM NONE [get_ports i2c_scl_io]
set_property OFFCHIP_TERM NONE [get_ports i2c_sda_io]

#usb_uart_rxd-PIO18 and usb_uart_txd-PIO19 are connected to Wiznet
set_property PACKAGE_PIN P3 [get_ports usb_uart_rxd]
set_property PACKAGE_PIN N3 [get_ports usb_uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_txd]
set_property PULLUP true [get_ports usb_uart_rxd]
set_property PULLUP true [get_ports usb_uart_txd]
set_property OFFCHIP_TERM NONE [get_ports usb_uart_rxd]
set_property OFFCHIP_TERM NONE [get_ports usb_uart_txd]

#usb_uart1_rxd and usb_uart1_txd are connected to CMOD-A7 UART-to-US
set_property PACKAGE_PIN J17 [get_ports usb_uart1_rxd]  
set_property PACKAGE_PIN J18 [get_ports usb_uart1_txd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart1_txd]
set_property PULLUP true [get_ports usb_uart1_rxd]
set_property PULLUP true [get_ports usb_uart1_txd]
set_property OFFCHIP_TERM NONE [get_ports usb_uart1_rxd]
set_property OFFCHIP_TERM NONE [get_ports usb_uart1_txd]
