----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 09/24/2019 05:38:48 PM
-- Design Name: 
-- Module Name: timers - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;

entity timers is
    generic(DATA_WIDTH : integer :=32);
	port(
	qa, qb, qc : out std_logic_vector(DATA_WIDTH-1 downto 0); --outputs from counters A, B and C
	tc : out std_logic; --preset on counter C reached
	bram_seg : out std_logic; -- active bram segment in auto mode
	timers_enabled: out std_logic; --timers enabled
	qp : in std_logic_vector(DATA_WIDTH-1 downto 0);  --preset for counter C
	clk : in std_logic; --signal clock
	clra, clrb, clrc : in std_logic; --clear individual counters 
	cea, ceb, cec : in std_logic; --enable individual counters
	lt_dir :in std_logic_vector(1 downto 0);	-- enable live-time counter (generated by PUP rejector) 
	a_mode, b_mode, c_mode : in std_logic;	-- if x_mode == 1 then counter x is live-time, otherwise it is real-time
	auto_start :in std_logic;  -- timers start/stop are controlled by FSM 
	manual_start :in std_logic  -- timers start/stop are controlled manually 
	);
end timers;

--
--
--
architecture Structural of timers is
 signal qa_i, qb_i, qc_i: std_logic_vector(31 downto 0);
 signal tc_i: std_logic;
 signal cea_i, ceb_i, cec_i: std_logic;
 signal clr_1kHz, lt_clr, lt_ce : std_logic;
 signal bram_seg_i, auto_clr, auto_en, timers_enabled_i, auto_tff_t, auto_tff_clk : std_logic;
 signal clra_i, clrb_i, clrc_i : std_logic;
 signal clk_ena, clk_enb, clk_enc : std_logic;
 signal clk_1kHz_ena, clk_1kHz_enb, clk_1kHz_enc : std_logic;
 signal clk_lt_en : std_logic;
 
 component counter
    generic(DATA_WIDTH : integer :=32);
	port(  clk, clr, ce : in std_logic;
	       q : out std_logic_vector(DATA_WIDTH-1 downto 0));
 end component;
 
 component comparator
    generic(DATA_WIDTH : integer :=32);
   	port(  a, b : in std_logic_vector(DATA_WIDTH-1 downto 0);
	       cmp : out std_logic);  
 end component;

 component fsm_auto_mode
    port ( auto_start, tc, clk : in std_logic;
           clr, en, bram_seg : out std_logic);
 end component;

component clock_1KHz_enable
	port(	clk, clr, ce : in std_logic;
			clk_1kHz_en : out std_logic);
end component;
			
component clk_lt_enable
	port(  clk, clr, ce: in std_logic;
           dir : in std_logic_vector(1 downto 0);
           lt_clk_en : out std_logic);
end component;
			





begin

-- internal signals that are used as output ports 
    qa <= qa_i;
    qb <= qb_i;
    qc <= qc_i;
    bram_seg <= bram_seg_i;
	tc <= tc_i;
	timers_enabled <= timers_enabled_i;
   
-- generate clock enable: it can be either clk_1kHz_en (for real time counter) or clk_lt_enx (for live time counter)
-- if x_mode is 1 then counter x is used as live time counter 
-- if x_mode is 0 then counter x is used as real time counter
    clk_ena <= clk_lt_en when a_mode = '1' else clk_1kHz_ena;
    clk_enb <= clk_lt_en when b_mode = '1' else clk_1kHz_enb;
    clk_enc <= clk_lt_en when c_mode = '1' else clk_1kHz_enc;    
	
--  global clock enable signal that is common for all counters	
	timers_enabled_i <= (auto_en or manual_start) and (not tc_i);
	
--  individual clock enable signals	
	cea_i <= cea and  timers_enabled_i; 
	ceb_i <= ceb and  timers_enabled_i; 
	cec_i <= cec and  timers_enabled_i; 
	
-- generate internal clear signals
	clra_i <= clra or auto_clr;
	clrb_i <= clrb or auto_clr;
	clrc_i <= clrc or auto_clr;
	
-- generate clear for clock enable generator which is used by live time counter
    lt_clr <= clra_i when a_mode = '1' else   --clk A assigned to measure LT
              clrb_i when b_mode = '1' else   --clk B assigned to measure LT
              clrc_i when c_mode = '1' else   --clk C assigned to measure LT
              '1';                                      --none  assigned to measure LT                                      

-- generate enable for clock enable generator which is used by live time counter
    lt_ce <= cea_i when a_mode = '1' else   --clk A assigned to measure LT
             ceb_i when b_mode = '1' else   --clk B assigned to measure LT
             cec_i when c_mode = '1' else   --clk C assigned to measure LT
             '0';                                               --none  assigned to measure LT
              
--instantiate clock enable generator which is used by live time counter
clk_lt_enable_inst : clk_lt_enable
	port map( clk=>clk, clr=>lt_clr, ce=>lt_ce, dir=>lt_dir, lt_clk_en=>clk_lt_en);

--instantiate 1kHz clock enable signal generator for counter A
clock_1KHz_enable_inst_A: clock_1KHz_enable
	port map( clk=>clk, clr=>clra_i, ce=>cea_i, clk_1kHz_en=>clk_1kHz_ena);

--instantiate 1kHz clock enable signal generator for counter B
clock_1KHz_enable_inst_B: clock_1KHz_enable
	port map( clk=>clk, clr=>clrb_i, ce=>ceb_i, clk_1kHz_en=>clk_1kHz_enb);

--instantiate 1kHz clock enable signal generator for counter C
clock_1KHz_enable_inst_C: clock_1KHz_enable
	port map( clk=>clk, clr=>clrc_i, ce=>cec_i, clk_1kHz_en=>clk_1kHz_enc);

--instantiate 32 bit counter A
counter_inst_A: counter
    generic map(DATA_WIDTH => 32)
	port map(clk=>clk, clr=>clra_i, ce=>clk_ena, q=>qa_i);

--instantiate 32 bit counter B
counter_inst_B: counter
    generic map(DATA_WIDTH => 32)
	port map(clk=>clk, clr=>clrb_i, ce=>clk_enb, q=>qb_i);

--instantiate 32 bit counter C
counter_inst_C: counter
    generic map(DATA_WIDTH => 32)
	port map(clk=>clk, clr=>clrc_i, ce=>clk_enc, q=>qc_i);
	
--instantiate comparator and generate terminal count output tc_i on counter C
comparator_inst: comparator
    generic map(DATA_WIDTH => 32)
	port map(a=>qc_i, b=>qp, cmp=>tc_i);	

--instantiate FSM for auto run_mode measurement and generate auto_clr, auto_en and bram_seg_i
fsm_auto_mode_inst: fsm_auto_mode
    port map ( auto_start=>auto_start, tc=>tc_i, clk=>clk,
               clr=>auto_clr, en=>auto_en, bram_seg=>bram_seg_i);
	



end Structural;




